### ISSUE TITLE
Performance benchmarks?

### ISSUE THREAD

**Issue by IanVS** [un-es/eslint-plugin-i#1]
I'm interested in perhaps using this fork, but I'm curious what real-world performance improvements you've seen compared with the upstream project.  It would be great to know how much faster I could expect this fork to be.

**Comment by JounQin** [comment]
I didn't have such benchmarks, you can easily run your own benchmark by `TIMING=1 npx eslint .` + changes between the different packages.

I've been using this fork for all my projects for a long time.

**Comment by IanVS** [comment]
Thanks for the suggestion.  I tried it out in my project, and didn't notice any real change between this fork and the upstream.  `import/namespace` was by far the rule that took the longest at around 8-9 seconds, with the total run taking ~48sec in all cases (without eslint cache).

**Comment by AndyOGo** [comment]
@JounQin 
Why is this closed?
I believe benchmarks to see the difference in performance are of high interest.
