### ISSUE TITLE
Add missing dependencies

### ISSUE THREAD

**Issue by LukeNotable** [un-es/eslint-plugin-i#14]
Trying to use this package for the first time, I got:
```
Error: Failed to load plugin 'import' declared in '.eslintrc.js': Cannot find module 'array.prototype.flatmap'
```

Looks like because [2.28.0](https://github.com/import-js/eslint-plugin-import/blob/main/CHANGELOG.md#2280---2023-07-27) added dependencies on:
* `array.prototype.flatmap`
* `array.prototype.findlastindex`
* `object.fromentries`

Which means they should be added to dependencies here too (unless they're being handled some other way).

Workaround is just to add the missing dependency as a dev dependency in my project.

**Comment by JounQin** [comment]
https://github.com/search?q=repo%3Aun-es%2Feslint-plugin-i%20array.prototype.flatmap&type=code

https://github.com/un-es/eslint-plugin-i/pull/11

I don't think it is used anywhere in this fork?

**Comment by silverwind** [comment]
Don't include all these polyfills imho. The original has like 50 extra dependencies because of these useless polyfill packages that are not needed with modern runtimes.

**Comment by JounQin** [comment]
I believe there is nothing to do here, if you still get this error, please provide a minimal but runnable reproduction.

**Comment by abieler-sap** [comment]
@LukeNotable, try to use version 2.28.1. It helped in our projects to get rid of the flatmap-error.
