### ISSUE TITLE
Does not recognize `i/extensions`

### ISSUE THREAD

**Issue by silverwind** [un-es/eslint-plugin-i#17]
It seems the plugin does not recognize this:

```yaml
settings:
  i/extensions: [".js", ".jsx", ".ts", ".tsx"]
```

It only worked after renaming to `import/extensions`.

**Comment by JounQin** [comment]
This is expected. Settings are not renamed, only the plugin name itself. The rule name prefix is based on plugin name, but setting keys are hard coded.

**Comment by silverwind** [comment]
Okay, might want to call this out in docs.

**Comment by JounQin** [comment]
PR welcome to add documentation.
