### ISSUE TITLE
`eslint-plugin-r`?

### ISSUE THREAD

**Issue by wojtekmaj** [un-es/eslint-plugin-i#19]
Hey there!

I thought I would follow the same path and create a fork of `eslint-plugin-react`, `eslint-plugin-r`, shaving off unnecessary polyfills. It's nowhere near as well done, as it lacks auto-release feature for example, but if anyone's interested, here it is:

https://github.com/wojtekmaj/eslint-plugin-r

**Comment by silverwind** [comment]
I'd definitely use this. Those polyfills need to go 😆.

**Comment by wojtekmaj** [comment]
I may have more definite, global solution, that doesn't require forking anything. But for the best experience, it requires Yarn.

There's an amazing project by @SukkaW that I wholeheartedly recommend:

https://github.com/wojtekmaj/yarn-plugin-nolyfill

It uses native capabilities of each package manager to replace problematic polyfills with ultralight wrappers using native functions.

It works wonders, but I wanted it to work transparently, with minimal friction.

And I built a Yarn plugins that replaces these dependency _during resolution_:

https://github.com/wojtekmaj/yarn-plugin-nolyfill

**Comment by silverwind** [comment]
I also toyed with the idea of bundling these eslint plugins with esbuild in my config package because install time is my primary concern. esbuild itself may have means to eliminate useless polyfills too.

As far as I can tell, eslint does [not offer a documented way](https://eslint.org/docs/latest/use/configure/plugins#configure-plugins) to load a plugin from a local directory, e.g. every plugin must also be a npm module, but I'm sure there would be workarounds available.

**Comment by wojtekmaj** [comment]
Found an interesting replacement: https://github.com/eslint-react/eslint-react

**Comment by JounQin** [comment]
> As far as I can tell, eslint does [not offer a documented way](https://eslint.org/docs/latest/use/configure/plugins#configure-plugins) to load a plugin from a local directory, e.g. every plugin must also be a npm module, but I'm sure there would be workarounds available.

@silverwind This should be easy to workaround with `npm install -D eslint-plugin-xxx@file:local/path`

**Comment by JounQin** [comment]
> Found an interesting replacement: [eslint-react/eslint-react](https://github.com/eslint-react/eslint-react)

Did you archive https://github.com/wojtekmaj/eslint-plugin-r due to the replacement plugin?

**Comment by wojtekmaj** [comment]
It seems that in case of eslint-plugin-react, nolyfill does the job well. So unless we can make it equally automated as eslint-plugin-i, I don't think it's worth maintaining. Fully automated though? Yes please!

**Comment by JounQin** [comment]
OK, I'll close this issue then.
