### ISSUE TITLE
Action is broken

### ISSUE THREAD

**Issue by ModyQyW** [un-es/eslint-plugin-i#2]
I think the rebase action is broken for  a while. Can you please fix it?

**Comment by ImOnMars** [comment]
Seems to just be due to [merge conflicts](https://github.com/un-es/eslint-plugin-i/actions/runs/4338779974/jobs/7575757683)

**Comment by AndyOGo** [comment]
@JounQin
`eslint-plugin-i` is behind `eslint-plugin-import`.
Latest should be `v2.27.5`, but is [`2.26.0-2`](https://www.npmjs.com/package/eslint-plugin-i/v/2.26.0-2) from 7 months ago.

**Comment by JounQin** [comment]
Done!
