### ISSUE TITLE
What is the ultimate purpose of this plug-in/fork?

### ISSUE THREAD

**Issue by jorisw** [un-es/eslint-plugin-i#27]
Could the README.md describe the purpose of this fork?

We're having performance issues with https://github.com/import-js/eslint-plugin-import, and would like to know how this fork may or may not help us.

**Comment by JounQin** [comment]
https://github.com/un-es/eslint-plugin-i/tree/fork-release?tab=readme-ov-file#eslint-plugin-i

> A fork of `eslint-plugin-import` using `get-tsconfig` to replace `tsconfig-paths` and heavy `typescript` under the hood.

See also #24

**Comment by jorisw** [comment]
Could the intro be expanded to explain which problem it solves?

**Comment by JounQin** [comment]
Does not the quote and related issues/PR make senses for you?

**Comment by jorisw** [comment]
My point is that upon discovering this plug-in on GitHub, the visitor should be made clear what the plug-in hopes to achieve.

The description:

> A fork of `eslint-plugin-import` using `get-tsconfig` to replace `tsconfig-paths` and heavy `typescript` under the hood.

Doesn't do that.

Which problem is address by this plug-in/fork ?

**Comment by JounQin** [comment]
1. cleanener dependencies
2. faster speed without heavy TypeScript dependency

And it is been rewritten to be an independent plugin, see also #26.

**Comment by jorisw** [comment]
So then I suggest adding to the README and repo description…

> This is a drop-in replacement for eslint-plugin-import which is faster, because of less heavy dependency on Typescript, and cleaner dependencies altogether.

**Comment by JounQin** [comment]
Thanks, PR welcome for `fork-release` branch.

**Comment by JounQin** [comment]
Close in favor of #28
